const PDFDocument = require('pdfkit')
const fs = require('fs')
const path = require('path')
const os = require('os')

const handler = async (m, { conn, usedPrefix, args }) => {
  if (!args[0]) {
    return m.reply(
      `⚠️ PDF ke liye text likho\nExample:\n${usedPrefix}pdf Assalam o Alaikum\nYeh meri PDF hai`
    )
  }

  await conn.sendMessage(m.chat, { react: { text: '📄', key: m.key } })

  try {
    const text = args.join(' ')
    const filePath = path.join(os.tmpdir(), `pdf_${Date.now()}.pdf`)

    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const stream = fs.createWriteStream(filePath)

    doc.pipe(stream)

    // Title
    doc
      .fontSize(18)
      .text('Generated by famofc', { align: 'center' })
      .moveDown()

    // Content
    doc
      .fontSize(12)
      .text(text, {
        align: 'left'
      })

    doc.end()

    stream.on('finish', async () => {
      await conn.sendMessage(
        m.chat,
        {
          document: fs.readFileSync(filePath),
          mimetype: 'application/pdf',
          fileName: 'document.pdf'
        },
        { quoted: m }
      )

      fs.unlinkSync(filePath)
      await conn.sendMessage(m.chat, { react: { text: '✅', key: m.key } })
    })

  } catch (e) {
    console.error('PDF ERROR:', e)
    await conn.sendMessage(m.chat, { react: { text: '❌', key: m.key } })
    m.reply('❌ PDF generate nahi hui')
  }
}

handler.command = ['pdf', 'topdf']
handler.category = 'tools'
handler.limit = false
handler.owner = false
handler.group = false

module.exports = handler